[package]
name = "TokenizedAssets"
version = "0.1.0"
authors = ["Your Name"]

[addresses]
Marketplace = "0x5f7d02e4c908d821d25e7a1df65250c440272bbd54872721f334fba67821c028" 

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"  # Use the latest stable revision or a specific commit
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
